steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:$SHORT_SHA'
      - '-t'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:latest'
      - '-f'
      - 'server/mercury-voice/Dockerfile'
      - 'server/mercury-voice/'
    id: 'build'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:$SHORT_SHA'
    id: 'push-sha'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:latest'
    id: 'push-latest'
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mercury-voice'
      - '--image'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:$SHORT_SHA'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--port'
      - '8080'
      - '--timeout'
      - '3600'
      - '--session-affinity'
      - '--set-env-vars'
      - 'NODE_ENV=production,GO_BACKEND_URL=https://ragbox-backend-100739220279.us-east4.run.app,DEFAULT_USER_ID=105836695160618550214,INWORLD_WORKSPACE=ragbx'
      - '--set-secrets'
      - 'INWORLD_API_KEY=ragbox-inworld-api-key:latest,INTERNAL_AUTH_SECRET=ragbox-internal-auth-secret:latest'
      - '--service-account'
      - 'ragbox-prod-cloudrun@$PROJECT_ID.iam.gserviceaccount.com'
    id: 'deploy'
    waitFor: ['push-sha']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '900s'

images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:$SHORT_SHA'
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/ragbox/mercury-voice:latest'
