/**
 * Infographic Renderer — JSON → PDF
 *
 * Converts infographic data points into a branded PDF using @react-pdf/renderer.
 * Runs server-side only (Node.js).
 */

import React from 'react'
import { renderToBuffer, Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'

/** Infographic data shape (matches AI output from prompts.ts) */
export interface InfographicData {
  title: string
  subtitle: string
  sections: {
    header: string
    dataPoints: {
      value: string
      label: string
      visualType: 'number' | 'percentage' | 'comparison' | 'timeline' | 'icon-stat'
    }[]
  }[]
  keyTakeaway: string
  callToAction: string
}

import { BRAND_BLUE, DARK_BG, CARD_BG, TEXT_PRIMARY, TEXT_SECONDARY, WARNING as ACCENT_AMBER, SUCCESS } from './colors'

const styles = StyleSheet.create({
  page: {
    backgroundColor: DARK_BG,
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 24,
    textAlign: 'center',
  },
  title: {
    fontSize: 28,
    color: TEXT_PRIMARY,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 12,
    color: TEXT_SECONDARY,
  },
  watermark: {
    fontSize: 8,
    color: TEXT_SECONDARY,
    textAlign: 'center',
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    fontSize: 14,
    color: BRAND_BLUE,
    fontWeight: 'bold',
    marginBottom: 10,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: BRAND_BLUE,
  },
  dataPointsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  card: {
    backgroundColor: CARD_BG,
    borderRadius: 6,
    padding: 14,
    width: '47%',
    marginBottom: 10,
  },
  cardValue: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  cardLabel: {
    fontSize: 10,
    color: TEXT_SECONDARY,
  },
  takeaway: {
    backgroundColor: CARD_BG,
    borderRadius: 6,
    padding: 16,
    marginTop: 10,
    borderLeftWidth: 3,
    borderLeftColor: ACCENT_AMBER,
  },
  takeawayLabel: {
    fontSize: 9,
    color: ACCENT_AMBER,
    fontWeight: 'bold',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  takeawayText: {
    fontSize: 12,
    color: TEXT_PRIMARY,
    lineHeight: 1.5,
  },
  cta: {
    textAlign: 'center',
    marginTop: 16,
  },
  ctaText: {
    fontSize: 10,
    color: SUCCESS,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 7,
    color: TEXT_SECONDARY,
  },
})

function getValueColor(visualType: string): string {
  switch (visualType) {
    case 'percentage':
      return SUCCESS
    case 'comparison':
      return ACCENT_AMBER
    case 'timeline':
      return BRAND_BLUE
    case 'number':
    case 'icon-stat':
    default:
      return TEXT_PRIMARY
  }
}

/**
 * Build the React-PDF document tree.
 * Using React.createElement since this is a server-only .ts file (no JSX transform).
 */
function buildInfographicDocument(data: InfographicData) {
  const e = React.createElement

  const sectionElements = data.sections.map((section, si) =>
    e(View, { key: `s-${si}`, style: styles.section },
      e(Text, { style: styles.sectionHeader }, section.header),
      e(View, { style: styles.dataPointsRow },
        section.dataPoints.map((dp, di) =>
          e(View, { key: `dp-${si}-${di}`, style: styles.card },
            e(Text, { style: { ...styles.cardValue, color: getValueColor(dp.visualType) } }, dp.value),
            e(Text, { style: styles.cardLabel }, dp.label),
          ),
        ),
      ),
    ),
  )

  return e(Document, null,
    e(Page, { size: 'A4', style: styles.page },
      e(Text, { style: styles.watermark }, 'RAGBOX SOVEREIGN STUDIO'),
      e(View, { style: styles.header },
        e(Text, { style: styles.title }, data.title),
        e(Text, { style: styles.subtitle }, data.subtitle),
      ),
      ...sectionElements,
      e(View, { style: styles.takeaway },
        e(Text, { style: styles.takeawayLabel }, 'Key Takeaway'),
        e(Text, { style: styles.takeawayText }, data.keyTakeaway),
      ),
      data.callToAction
        ? e(View, { style: styles.cta },
            e(Text, { style: styles.ctaText }, data.callToAction),
          )
        : null,
      e(Text, { style: styles.footer, fixed: true },
        `Generated by RAGbox Sovereign Studio — ${new Date().toISOString().split('T')[0]}`,
      ),
    ),
  )
}

/**
 * Render infographic data to a PDF Buffer.
 */
export async function renderInfographic(data: InfographicData): Promise<Buffer> {
  const doc = buildInfographicDocument(data)
  return Buffer.from(await renderToBuffer(doc))
}
