/**
 * Mind Map Renderer — Mermaid code → self-contained HTML
 *
 * Wraps the generated mermaid.js diagram in a standalone HTML file that
 * loads the mermaid library from CDN. User downloads and opens in any
 * browser — no Chromium or server-side rendering required.
 */

import { DARK_BG, CARD_BG, TERTIARY_BG, TEXT_PRIMARY, TEXT_SECONDARY, BRAND_BLUE, BORDER_DEFAULT } from './colors'

/**
 * Render a mermaid diagram string into a self-contained HTML Buffer.
 */
export function renderMindMap(title: string, mermaidCode: string): Buffer {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)} — RAGbox Mind Map</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: ${DARK_BG};
      color: ${TEXT_PRIMARY};
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
      padding: 2rem;
    }
    h1 {
      font-size: 1.5rem;
      margin-bottom: 0.5rem;
      text-align: center;
    }
    .watermark {
      font-size: 0.7rem;
      color: ${TEXT_SECONDARY};
      margin-bottom: 1.5rem;
    }
    .mermaid {
      background: ${CARD_BG};
      border-radius: 8px;
      padding: 2rem;
      max-width: 100%;
      overflow-x: auto;
    }
    .footer {
      margin-top: 2rem;
      font-size: 0.65rem;
      color: ${TEXT_SECONDARY};
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="watermark">RAGBOX SOVEREIGN STUDIO</div>
  <div class="mermaid">
${escapeHtml(mermaidCode)}
  </div>
  <div class="footer">Generated by RAGbox Sovereign Studio &mdash; ${new Date().toISOString().split('T')[0]}</div>

  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({
      startOnLoad: true,
      theme: 'dark',
      themeVariables: {
        primaryColor: '${BRAND_BLUE}',
        primaryTextColor: '${TEXT_PRIMARY}',
        primaryBorderColor: '${BORDER_DEFAULT}',
        lineColor: '${TEXT_SECONDARY}',
        secondaryColor: '${CARD_BG}',
        tertiaryColor: '${TERTIARY_BG}',
      },
    });
  </script>
</body>
</html>`

  return Buffer.from(html, 'utf-8')
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
